import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
	eslint.configs.recommended,
	...tseslint.configs.recommendedTypeChecked,
	{
		name:'mehrdadhub-eslint-config',
		languageOptions: {
			parserOptions: {
				project: true,
				sourceType: 'module',
				tsconfigRootDir: import.meta.dirname,
			},
		},
		rules: {
			'@typescript-eslint/interface-name-prefix': 'off',
			'@typescript-eslint/explicit-function-return-type': 'off',
			'@typescript-eslint/explicit-module-boundary-types': 'off',
			'@typescript-eslint/no-explicit-any': 'off',
			'@typescript-eslint/no-namespace':'off',
			'prettier/prettier': 'off',
			'no-mixed-spaces-and-tabs': 'off',
			'@typescript-eslint/no-unused-vars': [
				'warn',
				{
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
				},
			],
			'default-case':'off',
			'no-console': 'off',
			'func-names': 'off',
			'no-process-exit': 'off',
			'consistent-return': 'off',
			'object-shorthand': 'off',
			'class-methods-use-this': 'off',
			'no-underscore-dangle': 'off',
			'no-tabs': 'off',
			'@typescript-eslint/indent': 'off',
			'@typescript-eslint/no-redeclare': 'off',
			'import/prefer-default-export': 'off',
			'nonblock-statement-body-position': 'off',
			'operator-linebreak': 'off',
			'implicit-arrow-linebreak': 'off',
			'@typescript-eslint/naming-convention':'off',
			curly: ['error', 'multi'],
			'object-curly-newline': 'off',
			'max-classes-per-file': 'off',
			'no-trailing-spaces': 'off',
			'import/no-extraneous-dependencies': 'off',
			'no-restricted-syntax': 'off',
			'@typescript-eslint/no-unsafe-assignment':'off',
			'@typescript-eslint/no-unsafe-return':'off',
			'@typescript-eslint/no-unsafe-argument':'off',
			'@typescript-eslint/restrict-template-expressions':'off',
			'max-len': [
				'warn',
				{
					code: 120,
					comments: 120,
					ignoreComments: false,
					ignoreTrailingComments: true,
					ignoreUrls: true,
					ignoreStrings: true,
					ignoreTemplateLiterals: true,
					ignoreRegExpLiterals: true,
				},
			],
		},
	},
);
