name: Start Production Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(npm pkg get version --workspaces=false | tr -d '\"')" >> $GITHUB_ENV

      - name: Merge release branch to master and tag it
        run: |
          git checkout master
          git merge --no-ff ${{ github.ref_name }}
          git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
          git push origin master --follow-tags

      - name: Merge release branch to develop
        run: |
          git checkout develop
          git merge --no-ff ${{ github.ref_name }}
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      
      - name: Delete release branch from remote
        run: git push origin --delete ${{ github.ref_name }}
