name: Start Production Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(npm pkg get version --workspaces=false | tr -d '\"')" >> $GITHUB_ENV

      - name: Merge release to master
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          github_token: ${{ secrets.PAT }}
          message: ${{ github.ref_name }} branch merged with master for starting produntion deployment.
          
      - name: Merge release to develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ github.ref_name }} branch merged with develop for syncing latest changes.

      - name: Checkout release branch
        uses: actions/checkout@v4
        with: 
         ref: master

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.VERSION }}
          
      - name: Delete release branch from remote
        run: git push origin --delete ${{ github.ref_name }}
